### ISSUE TITLE
In vSphere Cloud Provider pods that are run as normal user can't write to the volumemounts

### ISSUE THREAD

**Issue by narendrakum** [vmware/vsphere-storage-for-kubernetes#54]
### Issue Description :
If the underlying storage is vpshere-volume only pods which is running as root user are able to write in the mount path. When the pod is run as normal user we see a permission denied issue. We have tried manually changing the permissions of files which is present on kubevols directory in datastore but still when it mounts inside the pod, it is mounting with default ownership as root. 
Is it an expected behavior when using vsphere-volume? 
we have tried hostPath and it works for normal users as well.

### How to reproduce it :
**Pod yaml**
```
root@cli-vm:~# cat busybox1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
spec:
  containers:
  - args:
    - sleep
    - "1000000"
    image: busybox
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
      - mountPath: /data/busybox
        name: busybox-storage
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  securityContext:
    runAsUser: 1000
  volumes:
    - name: busybox-storage
      persistentVolumeClaim:
        claimName: pvcsc-spbm
```
**Resource Status:**
```
root@cli-vm:~# kubectl get pod,pv,pvc,sc
NAME           READY   STATUS    RESTARTS   AGE
pod/busybox1   1/1     Running   0          80m
NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                STORAGECLASS     REASON   AGE
persistentvolume/pvc-89fbd3b2-dea6-11e9-ae67-00505688d930   2Gi        RWO            Delete           Bound    default/pvcsc-spbm   vmware-default            7h37m
NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
persistentvolumeclaim/pvcsc-spbm   Bound    pvc-89fbd3b2-dea6-11e9-ae67-00505688d930   2Gi        RWO            vmware-default   7h38m
NAME                                                   PROVISIONER                    AGE
storageclass.storage.k8s.io/vmware-default (default)   kubernetes.io/vsphere-volume   7h46m
```
**Write error inside the pod:**
```
root@cli-vm:~# kubectl exec busybox1 -it sh
/ $ id
uid=1000 gid=0(root)
/ $ cd /data/busybox/
/data/busybox $ mkdir test
mkdir: can't create directory 'test': Permission denied
/data/busybox $ ls -ld /data/busybox/
drwxr-xr-x    3 root     root          4096 Sep 24 12:27 /data/busybox/
```
**Changing the permission of PV file inside datastore:**
```
[root@esx-01a:/vmfs/volumes/5bf02293-ccefd9dc-5cbe-005056064e81/kubevols] ls -lth
-rw-------    1 root     root         545 Sep 24 08:37 kubernetes-dynamic-pvc-89fbd3b2-dea6-11e9-ae67-00505688d930.vmdk
-rw-------    1 root     root        2.0G Sep 24 08:37 kubernetes-dynamic-pvc-89fbd3b2-dea6-11e9-ae67-00505688d930-flat.vmdk

[root@esx-01a:/vmfs/volumes/5bf02293-ccefd9dc-5cbe-005056064e81/kubevols] chown 1000:1000 kubernetes-dynamic-pvc-89fbd3b2-dea6-11e9-ae67-00505688d930-flat.vmdk kubernetes-dynamic-pvc-89fbd3b2-dea6-11e9-ae67-
00505688d930.vmdk
[root@esx-01a:/vmfs/volumes/5bf02293-ccefd9dc-5cbe-005056064e81/kubevols] ls -l
total 1686528
-rw-------    1 da-user  da-user  2147483648 Sep 24 14:55 kubernetes-dynamic-pvc-89fbd3b2-dea6-11e9-ae67-00505688d930-flat.vmdk
-rw-------    1 da-user  da-user        545 Sep 24 14:55 kubernetes-dynamic-pvc-89fbd3b2-dea6-11e9-ae67-00505688d930.vmdk
```
**Write error inside the pod after the permission change:**
```
/data/busybox $ ls -ld /data/busybox
drwxr-xr-x    3 root     root          4096 Sep 24 12:27 /data/busybox
/data/busybox $ mkdir test
mkdir: can't create directory 'test': Permission denied
```
