### ISSUE TITLE
vsphere mount 

### ISSUE THREAD

**Issue by shahbour** [vmware/vsphere-storage-for-kubernetes#56]
Currently kube-api and kube-controller does not mount the whole /etc/kubernetes folder so to be able to add

```
    - --cloud-provider=vsphere
    - --cloud-config=/etc/kubernetes/vsphere.conf
```

we also need to update to mounts 

```
    - mountPath: /etc/kubernetes/vsphere.conf
      name: vsphere
      readOnly: true
```
and
```
  - hostPath:
      path: /etc/kubernetes/vsphere.conf
      type: FileOrCreate
    name: vsphere
```

This is missing in the documentation
